---
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

- hosts: localhost
  connection: local
  become: yes

  gather_facts: yes

  tags:
  - dot-bashrc

  vars:
    # Current UID
    current_uid: "{{ c_uid|d(lookup('env','UID')) }}"
    # Current dir.
    current_dir: "{{ c_dir|d(lookup('pipe','pwd -P')) }}"
    # User
    user_name: "{{ uid|d(lookup('env','USER')) }}"
    user_group: "{{ gid|d(lookup('pipe','id -gn %s'|format(user_name))) }}"
    user_homedir: "{{ home_dir|d(lookup('env','HOME')) }}"
    user_confdir: "{{ '%s/.config'|format(user_homedir) }}"
    # bashrc install type
    bashrc_install_system: "{{ system|d(true) }}"
    # bashrc install prefix
    bashrc_install_prefix: "{{
      prefix if prefix|d('')|length > 0 else
      user_confdir if system|d(true) == false else none }}"

  roles:
  - bashrc

