---
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

- hosts: localhost
  connection: local
  become: "{{ global|d(false,true)|bool }}"

  gather_facts: yes

  tags:
  - dot-bashrc

  vars:
    # Global install
    bashrc_install_global: "{{ global|d(false,true)|bool }}"
    # Swtup SKEL
    bashrc_install_skel: "{{ skel|d(false,true)|bool }}"

  roles:
  - { role: ./.. }

