---
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

- hosts: localhost
  connection: local
  become: yes

  gather_facts: yes

  tags:
  - dot-bashrc

  vars:
    # Current UID
    current_user: "{{ c_user|d(lookup('env','USER')|d(lookup('pipe','id -un')) }}"
    # Current dir.
    current_dir: "{{ c_dir|d(lookup('pipe','pwd -P')) }}"
    # User
    user_name: "{{ user|d(c_user) }}"
    user_group: "{{ group|d(lookup('pipe','id -gn %s'|format(user_name))) }}"
    user_homedir: "{{ home_dir|d(lookup('env','HOME')) }}"
    user_confdir: "{{ '%s/.config'|format(user_homedir) }}"
    # bashrc install type
    dot_bashrc_install_for: "{{ 'system' if system|d(true) else 'user' }}"
    # bashrc install prefix
    dot_bashrc_install_prefix: "{{
      install_dir if install_dir|d('')|length > 0 else
      user_confdir if system|d(true) == false else
      none }}"

  roles:
  - bashrc

