---
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

- hosts: localhost
  connection: local
  become: yes

  gather_facts: yes

  tags:
  - dot-bashrc

  vars:
    current_uid: "{{ c_uid|d(lookup('env','UID')) }}"
    current_dir: "{{ c_dir|d(lookup('pipe','pwd -P')) }}"
    # User specification
    user_name: "{{ user_name|d(lookup('env','USER')) }}"
    user_group: "{{ user_group|d(lookup('pipe','id -gn %s'|format(user_name))) }}"
    user_homedir: "{{ home_dir|d(lookup('env','HOME')) }}"
    user_configdir: "{{ '%s/.config'|format(user_homedir) }}"
    # bashrc install prefix
    bashrc_install_prefix: "{{ user_configdir if system|d(true) == false else none }}"

  roles:
  - bashrc

