---
# tasks file for dot-bashrc
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

- block:

  - name: "bashrc | userhomedir - {{ bashrc_bash_user|d('???',true) }} | Facts user."
    set_fact:
      bashrc_userhomedir_user: "{{
        tests_owner|d((
        bashrc_bash_user|string|trim
        if bashrc_bash_user|d('',true)|string|trim|length > 0 else
        lookup('pipe','id -un')
        ),true) }}"

  - name: "bashrc | userhomedir - {{ bashrc_userhomedir_user|d('???',true) }} | Stat user."
    user:
      name: "{{ bashrc_userhomedir_user }}"
      state: present
    register: bashrc_userhomedir_user_st
    ignore_errors: yes

  - name: "debug"
    debug:
      msg: "{{ bashrc_userhomedir_user_st.home }} is_dir {{ bashrc_userhomedir_user_st.home|is_dir }}"

  - name: "bashrc | userhomedir - {{ bashrc_userhomedir_user|d('???',true) }} | Stat user homedir."
    stat:
      path: "{{
        bashrc_userhomedir_user_st.home
        if bashrc_userhomedir_user_st.home|d('-',true)|is_dir else
        (bashrc_distribution|match('^macos'))|ternary('/home/%s','/Users/%s')|
        format(tests_owner|d('test',true)) }}"
    register: bashrc_userhomedir_st
    ignore_errors: yes
    when: bashrc_userhomedir_user_st|d(none) is not none

  - name: "bashrc | userhomedir - {{ bashrc_userhomedir_user|d('???',true) }} | Set fact user homedir."
    set_fact:
      bashrc_userhomedir_path: "{{
        '%s'|format((
        bashrc_userhomedir_st.stat.path|string|trim
        if ((bashrc_userhomedir_st|d({},true)).stat|d({},true)).isdir|d(false,true)
        and ((bashrc_userhomedir_st|d({},true)).stat|d({},true)).path|d('',true)|length > 0 else
        none
        )) }}"
      bashrc_userhomedir_owner: "{{
        tests_owner|d((
        bashrc_userhomedir_st.stat.pw_name|d(none)
        if ((bashrc_userhomedir_st|d({},true)).stat|d({},true)).isdir|d(false,true) else
        none
        ),true) }}"
      bashrc_userhomedir_group: "{{
        tests_group|d((
        bashrc_userhomedir_st.stat.gr_name|d(none)
        if ((bashrc_userhomedir_st|d({},true)).stat|d({},true)).isdir|d(false,true) else
        none
        ),true) }}"

  tags:
  - bashrc-userhomedir

