---
# defaults file for bashrc
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

# Meta data for this role.
bashrc_meta: |
    {{ lookup('file',('%s/meta/main.yml'|format(role_path)))|from_yaml }}

# If necessary,
# define a default value with a variable name beginning with "bashrc_" here.

bashrc_os_family: "{{ ansible_os_family|d('',true)|trim|lower }}"

bashrc_distribution: "{{ ansible_distribution|d('',true)|trim|lower }}"

bashrc_base_dir: "{{ '/etc'|realpath }}"

bashrc_skel_dir: "{{
  '%s'|format((
  (bashrc_distribution|match('^macos')|ternary(
  '/System/Library/User Template/Non_localized','/etc/skel')
  ))|realpath }}"

bashrc_owner: 'root'

bashrc_group: "{{
  (bashrc_os_family|match('^darwin'))|ternary('admin','wheel') }}"

bashrc_dir_mode: '0755'

bashrc_file_mode: '0644'

bashrc_script_mode: '0755'

