---
# tasks file for bashrc
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

#
# Available:
#  bashrc_install_prefix
#  bashrc_base_dir
#

- block:

  - name: "bashrc | global | Facts - Build a install path."
    set_fact:
      bashrc_install_path: "{{
        '%s%s'|format(tests_prefix_dir|d('',true),(
        bashrc_install_prefix|trim
        if bashrc_install_prefix|d(none)
        and bashrc_install_prefix|d('',true)|trim|length > 0 else
        bashrc_base_dir|d('/etc',true)
        ))|realpath }}"

  - name: "bashrc | global | Facts - Set owner and group."
    set_fact:
      bashrc_install_owner: "{{
        tests_owner|d(bashrc_owner|d('root',true)) }}"
      bashrc_install_group: "{{
        tests_group|d(bashrc_group|d('root',true)) }}"

  - name: "bashrc | global | Facts - File and Dir name."
    set_fact:
      bashrc_bashrcdir_name: "{{ 'bash.bashrc.d' }}"
      bashrc_bashrc_name: "{{ 'bash.bashrc' }}"
      bashrc_profile_name: "{{ 'bash.profile' }}"

  - name: "bashrc | global | Facts - Build a path of 'bash.bashrc.d'."
    set_fact:
      bashrc_bashrcdir_path: "{{
        '%s/%s'|format(bashrc_install_path,bashrc_bashrcdir_name) }}"
      bashrc_bash_rc_file_path: "{{
        '%s/%s'|format(bashrc_install_path,bashrc_bashrc_name) }}"
      bashrc_bash_profile_path: "{{
        '%s/%s'|format(bashrc_install_path,bashrc_profile_name) }}"

  tags:
  - always

- block:

  - name: "bashrc | global | Installing bashrc."
    include: "install.yml"

  - name: "bashrc | global | Symlinks"
    file:
      src: "{{ _symlink.src|trim }}"
      dest: "{{ _symlink.dest|trim }}"
      state: link
      force: yes
    with_items: "{{ _symlink_files|d([]) }}"
    loop_control:
      loop_var: _symlink
    when: (_symlink|d({})).src|d('',true)|trim|length > 0)
          and (_symlink|d({})).dest|d('',true)|trim|length > 0

  vars:
    _symlink_files:
    - src: "{{ '%s/%s'|format(bashrc_install_path,bashrc_bashrc_name) }}"
      dest: "{{ '%s/bashrc'|format(bashrc_install_path) }}"
    - src: "{{ '%s/%s'|format(bashrc_install_path,bashrc_profile_name) }}"
      dest: "{{ '%s/profile'|format(bashrc_install_path) }}"
  tags:
  - bashrc-install-global

- block:

  - name: "bashrc | global | Installing user template."
    include: "skel_template.yml"

  when: bashrc_setup_skel|d(true,true) == true
  tags:
  - bashrc-install-skel-for-global
