---
# tasks file for bashrc
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

- block:

  - name: bashrc | install | backup | Create a directory for backup.
    file:
      path: "{{ _backup_to_dir }}"
      state: directory
      owner: "{{ bashrc_install_owner }}"
      group: "{{ bashrc_install_group }}"
      mode: "{{ bashrc_dir_mode|d('0755') }}"
    register: _backup_to_dir_mkdir

  - name: bashrc | install | backup | Stat backup directory.
    stat:
      path: "{{ _backup_to_dir }}"
    register: _backup_to_dir_st
    when: _backup_to_dir_mkdir|changed

  - name: bashrc | install | backup | Backup the original files.
    copy:
      src: "{{ '%s/%s'|format(_backup_from_dir,_bashrc_backup_file) }}"
      dest: "{{ '%s/%s'|format(_backup_to_dir,_bashrc_backup_file) }}"
      remote_src: true
    ignore_errors: true
    with_items:
    - bashrc
    - profile
    - bash.bashrc
    - bash.profile
    loop_control:
      loop_var: _bashrc_backup_file
    when: _backup_to_dir_st|d(none) is not none
          and _backup_to_dir_st.stat|d(none) is not none
          and _backup_to_dir_st.stat.isdir|d(false) == true

  vars:
    _backup_from_dir: "{{ bashrc_install_path }}"
    _backup_to_dir: "{{ '%s/%s'|format(_backup_from_dir,'._bashrc-origin') }}"
  tags:
  - bashrc-install-backup-origins

- block:

  - name: "bashrc | install | bash.bashrc.d | Create a '{{ bashrc_bashrcdir_name }}' directory."
    file:
      path: "{{ bashrc_bashrcdir_path }}"
      state: directory
      owner: "{{ bashrc_install_owner }}"
      group: "{{ bashrc_install_group }}"
      mode: "{{ bashrc_dir_mode|d('0755') }}"

  - name: "bashrc | bash.bashrc.d | Install '{{ bashrc_bashrcdir_name }}' files"
    synchronize:
      src: 'etc/bash.bashrc.d/'
      dest: "{{ bashrc_bashrcdir_path }}/"
      checksum: yes
      compress: yes
      delete: yes
      links: yes
      recursive: yes
    register: _bashrc_files_installed

  - name: "bashrc | install | bash.bashrc.d | Find files and dirs under the {{ bashrc_bashrcdir_name }}/"
    find:
      paths: "{{ bashrc_bashrcdir_path }}"
      recurse: yes
    register: _bashrc_find

  - name: "bashrc | install | bash.bashrc.d | Change mode all files and dirs under the {{ bashrc_bashrcdir_name }}/"
    file:
      path: "{{ _bashrc_find_file.path }}"
      state: touch
      owner: "{{ bashrc_install_owner }}"
      group: "{{ bashrc_install_group }}"
      mode: "{{ bashrc_file_mode|d('0644')
                if _bashrc_find_file.isdir == false else
                bashrc_dir_mode|d('0755') }}"
    with_items: "{{ _bashrc_find.files|d([]) }}"
    loop_control:
      loop_var: _bashrc_find_file
    when: _bashrc_find_file|d(none) is not none
          and _bashrc_find_file.path|d(none) is not none

  - name: "bashrc | install | bash.bashrc.d | Find shell files under the {{ bashrc_bashrcdir_name }}/"
    find:
      paths: "{{ bashrc_bashrcdir_path }}"
      patterns: "*.sh*"
      recurse: yes
    register: _bashrc_find_sh

  - name: "bashrc | install | bash.bashrc.d | Find shell files under the {{ bashrc_bashrcdir_name }}/bin"
    find:
      paths: "{{ bashrc_bashrcdir_path }}/bin"
      file_type: file
      recurse: yes
    register: _bashrc_find_bin

  - name: "bashrc | install | bash.bashrc.d | Change mode all shell script files"
    file:
      path: "{{ _bashrc_find_script.path }}"
      state: touch
      owner: "{{ bashrc_install_owner }}"
      group: "{{ bashrc_install_group }}"
      mode: "{{ bashrc_script_mode|d('0755') }}"
    with_flattened:
    - "{{ _bashrc_find_sh.files|d([]) }}"
    - "{{ _bashrc_find_bin.files|d([]) }}"
    loop_control:
      loop_var: _bashrc_find_script
    when: _bashrc_find_script|d(none) is not none
          and _bashrc_find_script.path|d(none) is not none

  tags:
  - bashrc-install-bashrc-dir

- block:

  - name: "bashrc | install | template | Install the rc files from template"
    template:
      src: "{{ 'etc/%s.j2'|format(_bashrc_template.src) }}"
      dest: "{{ '%s/%s'|format(bash_install_path,
                _bashrc_template.dest|d(_bashrc_template.src)) }}"
      owner: "{{ bashrc_install_owner }}"
      group: "{{ bashrc_install_group }}"
      mode: "{{ bashrc_file_mode|d('0644') }}"
    with_items: "{{ _bashrc_template_files|d([]) }}"
    loop_control:
      loop_var: _bashrc_template
    when: _bashrc_template|d(none) is not none
          and _bashrc_template.src|d('')|length > 0

  vars:
    _bashrc_template_files:
    - src: 'bash.bashrc'
      dest: "{{ bashrc_bashrc_name }}"
    - src: 'bash.profile'
      dest: "{{ bashrc_prodile_name }}"
    - src: 'vim/vimrc'
      dest: none
  tags:
  - bashrc-install-template-files

