---
# tasks file for bashrc
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

- block:

  - name: "bashrc | bashrc for ..."
    set_fact:
      bashrc_install_for: "{{
        dot_bashrc_install_for
        if dot_bashrc_install_for|d('')|length > 0 else
        'system'
        if bashrc_install_system|d(true) else
        'user' }}"
    when: bashrc_install_for|d('')|length <= 0

  - name: "bashrc | Setup bashrc for {{ bashrc_install_for }}. "
    include: "{{ '%s.yml'|format(bashrc_install_for|d('system') }}"
    when: bashrc_install_for|d('')|lengh > 0

  tags:
  - always

- block:

  - name: "bashrc | Set up user's environment "
    include: "skel.yml"
    with_items: "{{ bashrc_bash_users|d([]) }}"
    loop_control:
      loop_var: bashrc_bash_user
    when: bashrc_bash_user|d('')|length > 0

  when: bashrc_bash_users|d([])|length > 0
  vars:
    bashrc_skel:
      install_path: "{{ bashrc_install_prefix }}"
      bashrcdir_path: "{{ bashrc_bashrcdir_path }}"
      bashrc_path: "{{
        '%s/%s'|format(
        bashrc_install_path,bashrc_rc_ile_name) }}"
      profile_path: "{{
        '%s/%s'|format(
        bashrc_install_path,bashrc_profile_name) }}"
      dir_mode: "{{ bashrc_dir_mode|d('0755') }}"
      file_mode: "{{ bashrc_file_mode|d('0644') }}"
      script_mode: "{{ bashrc_script_mode|d('0755') }}"
  tags:
  - bashrc-skel

