---
# tasks file for bashrc
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

- block:

  - name: "bashrc | bashrc for ..."
    set_fact:
      bashrc_install_for: "{{
        (bashrc_install_global|d(false,true))|ternary('global','local') }}"
      bashrc_setup_skel: "{{
         bashrc_install_skel|d(none) }}"
      bashrc_bash_user: "{{
        (bashrc_install_user|d('',true)|trim|length > 0)|ternary(
        bashrc_install_user|trim,lookup('pipe','id -un') ) }}"

  tags:
  - always

- block:

  - name: "bashrc | Setup bashrc for '{{ bashrc_install_for }}'."
    include: "{{ 'install_%s.yml'|format(bashrc_install_for) }}"

  tags:
  - bashrc-install

