---
# tasks file for bashrc

- name: bashrc | Set facts
  set_fact:
    bash_bashrc_d_dir: "{{ '%s/%s'|format(prefix_dir|d(''),bash_bashrc_path) }}"
    bash_bashrc_files_path: "{{ bash_bashrc_files_path|d(bash_bashrc_path) }}"
  vars:
    bash_bashrc_path: 'etc/bash.bashrc.d'
  tags:
  - always

- block:

  - name: bashrc | backup | Create a directory for backup.
    file:
      path: "{{ _bashrc_backup_todir }}"
      state: directory
      owner: "{{ test_owner|d('root') }}"
      group: "{{ test_group|d('root') }}"
      mode: 0755
    register: backup_dir_mkdir

  - name: bashrc | backup | Stat backup directory.
    stat:
      path: "{{ _bashrc_backup_todir }}"
    register: backup_dir_stat
    when: backup_dir_mkdir|changed

  - name: bashrc | backup | Backup the original files.
    copy:
      src: "{{ _bashrc_origin_dir }}/{{ item }}"
      dest: "{{ _bashrc_backup_todir }}/{{ item }}"
      remote_src: true
    ignore_errors: true
    with_items: 
    - bashrc
    - profile
    - bash.bashrc
    - bash.profile
    when: backup_dir_stat.stat|d(none) is not none
          and backup_dir_stat.stat.isdir|d(false) == true

  vars:
    _bashrc_origin_dir: "{{ '%s/%s'|format(prefix_dir|d(''),'etc') }}"
    _bashrc_backup_todir: "{{ '%s/%s'|format(_bashrc_origin_dir,'._bashrc-origin') }}"
  
  tags:
  - bashrc-backup-origin

- name: "bashrc | Create a '{{ bash_bashrc_d_dir|basename }}' directory."
  file:
    path: "{{ bash_bashrc_d_dir }}/"
    state: directory
    owner: "{{ test_owner|d(bash_bashrc_d_dir_owner|d('root')) }}"
    group: "{{ test_group|d(bash_bashrc_d_dir_group|d('root')) }}"
    mode: "{{ bash_bashrc_d_dir_mode|d('0755') }}"
  tags:
  - install-bash-bashrc-dir-mkdir
  - install-bash-bashrc-dir

- name: bashrc | Stat '{{ bash_bashrc_d_dir|basename }}' directory.
  stat: path="{{ bash_bashrc_d_dir }}/"
  register: bash_bashrc_d_stat
  tags:
  - install-bash-bashrc-dir-stat
  - install-bash-bashrc-dir

- name: "bashrc | Install '{{ bash_bashrc_d_dir|basename }}' files"
  synchronize:
    src: "{{ bash_bashrc_files_path }}/"
    dest: "{{ bash_bashrc_d_dir }}/"
    checksum: yes
    compress: yes
    delete: yes
    links: yes
    recursive: yes
  register: bash_bashrc_files_installed
  when: bash_bashrc_d_stat.stat|d(none) is not none
        and bash_bashrc_d_stat.stat.isdir|d(false) == true
  tags:
  - install-bash-bashrc-dir

- block:

  - name: "bashrc | Find shell files under the {{ bash_bashrc_d_dir }}/"
    find:
      paths: "{{ bash_bashrc_d_dir }}"
      patterns: "*.sh*"
      recurse: yes
    register: bash_bashrc_find_sh

  - name: "bashrc | Find shell files under the {{ bash_bashrc_d_dir }}/bin"
    find:
      paths: "{{ bash_bashrc_d_dir }}/bin"
      file_type: file
      recurse: yes
    register: bash_bashrc_find_bin

  - name: bashrc | Change mode all shell files
    file:
      path: "{{ item.path }}"
      state: touch
      owner: "{{ test_owner|d(bash_bashrc_script_owner|d('root')) }}"
      group: "{{ test_group|d(bash_bashrc_script_group|d('root')) }}"
      mode: "{{ bash_bashrc_script_mode|d('0755') }}"
    with_flattened:
    - "{{ bash_bashrc_find_sh.files|d([]) }}"
    - "{{ bash_bashrc_find_bin.files|d([]) }}"
    when: item.path|d(none) is not none

  when: bash_bashrc_files_installed|changed
  tags:
  - change-mode-files

- block:

  - name: bashrc | Install rc files
    template:
      src: "etc/{{ item.src }}.j2"
      dest: "{{ '%s/%s'|format(prefix_dir|d(''),'etc') }}/{{ item.src }}"
      owner: "{{ test_owner|d(bash_bashrc_rc_files_owner|d('root')) }}"
      group: "{{ test_group|d(bash_bashrc_rc_files_group|d('root')) }}"
      mode: "{{ bash_bashrc_rc_files_mode|d('0644') }}"
    register: bash_bashrc_install_rc_files
    with_items: "{{ bash_bashrc_rc_files|d([]) }}"
    when: item.src|d(none) is not none

  - name: bashrc | Symlinks rc files
    file:
      src: "{{ '%s/%s'|format(prefix_dir|d(''),'etc') }}/{{ item.src }}"
      dest: "{{ '%s/%s'|format(prefix_dir|d(''),'etc') }}/{{ item.dest|d(item.src) }}"
      state: link
      force: yes
    with_items: "{{ bash_bashrc_rc_files|d([]) }}"
    when: bash_bashrc_install_rc_files|changed
          and item.src|d(none) is not none

  vars:
    bash_bashrc_rc_files:
    - { src: bash.bashrc, dest: bashrc }
    - { src: bash.profile, dest: profile }
  tags:
  - symlink-bash-files

