---
# tasks file for bashrc
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

- name: bashrc | setup-user | user_homedir
  fail:
    msg: "{{ user_homedir }}: not specified."
  when: user_homedir|d('')|length <= 0
        or user_homedir|is_dir == false

- name: bashrc | setup-user | Stat user homedir
  stat:
    path: "{{ '%s%s'|format(tests_prefix_dir|d(''),user_homedir)|realpath }}"
  register: user_homedir_st
  when: user_homedir|d('')|length > 0

- name: bashrc | setup-user | Set facts owner and group
  set_fact:
    bash_bashrc_install_owner: "{{
      tests_owner|d(
      user_name
      if user_name|d('')|length > 0 else
      _user_homedir_pw_name
      if _user_homedir_pw_name|d('')|length > 0 else
      bash_bashrc_owner|d('root')) }}"
    bash_bashrc_install_group: "{{
      tests_group|d(
      user_group
      if user_group|d('')|length > 0 else
      _user_homedir_gr_name
      if _user_homedir_gr_name|d('')|length > 0 else
      bash_bashrc_group|d('root')) }}"
    bashrc_install_user_home: "{{
      true
      if bashrc_install_prefix|d('')|length > 0
      and bashrc_install_prefix == user_homedir|d('')
      else false }}"
  vars:
    _user_homedir_pw_name: "{{
      user_homedir_st.stat.pw_name
      if user_homedir_st.stat|d(none) is not none
      and user_homedir_st.stat.pw_name|d(none) is not none
      else none }}"
    _user_homedir_gr_name: "{{
      user_homedir_st.stat.gr_name
      if user_homedir_st.stat|d(none) is not none
      and user_homedir_st.stat.gr_name|d(none) is not none
      else none }}"

- name: bashrc | setup-user | Set facts rc-file name.
  set_fact:
    bash_bashrc_bashrc_dir_name: "{{
      '%s%s'|format(
      ('.' if bashrc_install_user_home|d(false) else ''),
      'bash.bashrc.d' }}"
    bash_bashrc_rc_file_name: "{{
      '%s%s'|format(
      ('.' if bashrc_install_user_home|d(false) else ''),
      'bash.bashrc' }}"
    bash_bashrc_profile_name: "{{
      '%s%s'|format(
      ('.' if bashrc_install_user_home|d(false) else ''),
      'bash.profile' }}"

- name: bashrc | setup-user | Create a bashrc install prefix.
  file:
    path: "{{ bashrc_install_prefix }}"
    state: directory
    owner: "{{ bash_bashrc_install_owner }}"
    group: "{{ bash_bashrc_install_group }}"
    mode: "{{ bash_bashrc_dir_mode|d('0755') }}"

