---
# tasks file for bashrc
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

- block:

  - name: bashrc | skel({{ bashrc_bash_user|d('???') }}) | Get homedir.
    include: "userhomedir.yml"

  - name: bashrc | skel({{ bashrc_bash_user|d('???') }}) | Check the user homedir.
    fail:
      mag: "User '{{ bashrc_bash_user|d('???') }}' is not present in the this system."
    when: bashrc_userhomedir_path|d('',true)|trim|length <= 0
          or bashrc_userhomedir_path|realpath|is_dir == false

  when: bashrc_skel_install_to|d('-',true)|string|is_dir == false
  tags:
  - bashrc-skel-user-homedir

- block:

  - name: "bashrc | skel({{ bashrc_bash_user|d('???') }}) | Lookup template files and dirs in {{ bashrc_skel_user_template_path|d('???',true) }}."
    include: 'skel_files.yml'

  - name: "bashrc | skel({{ bashrc_bash_user|d('???') }}) | Convert absolute path to relative path."
    include: 'skel_copy.yml'
    ignore_errors: yes
    with_items: "{{ (bashrc_skel_files_result|d({},true)).files|d([],true) }}"
    loop_control:
      loop_var: bashrc_skel_template_file
    when: (bashrc_skel_template_file|d({},true)).path|d('',true)|trim|length > 0

  vars:
    bashrc_skel_template_path: "{{
      '%s'|format((
      bashrc_skel_dir|string|trim
      if bashrc_skel_dir|d('-',true)|string|trim|is_dir else
      '%s%s'|format(tests_prefix_dir|d('',true),(
      bashrc_default_skel_dir|d(
      (bashrc_distribution|match('^macos'))|ternary(
      '/System/Library/User Template/Non_localized','/etc/skel')
      ,true)))
      ))|realpath }}"
    bashrc_skel_install_path: "{{
      '%s'|format((
      bashrc_skel_todir|string|trim
      if bashrc_skel_todir|d('-',true)|string|trim|is_dir else
      bashrc_userhomedir_path|d('',true)|string|trim
      ))|realpath }}"
  tags:
  - bashrc-skel-user

