---
# tasks file for bashrc
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

- block:

  - name: "bashrc | system | Facts - Build a install path."
    set_fact:
      bashrc_install_path: "{{
        '%s%s'|format(tests_prefix_dir|d(''),(
        bashrc_install_prefix
        if bashrc_install_prefix|d('')|length > 0 else
        bashrc_base_dir|d('/etc')
        ))|realpath }}"

  - name: "bashrc | system | Facts - Set owner and group."
    set_fact:
      bashrc_install_owner: "{{
        tests_owner|d(bashrc_owner|d('root')) }}"
      bashrc_install_group: "{{
        tests_group|d(bashrc_group|d('root')) }}"

  - name: "bashrc | system | Facts - File and Dir name."
    set_fact:
      bashrc_bashrcdir_name: "{{ 'bash.bashrc.d' }}"
      bashrc_bashrc_name: "{{ 'bash.bashrc' }}"
      bashrc_profile_name: "{{ 'bash.profile' }}"

  - name: "bashrc | system | Facts - Build a path of 'bash.bashrc.d'."
    set_fact:
      bashrc_bashrcdir_path: "{{
        '%s/%s'|format(bashrc_install_path,bashrc_bashrcdir_name) }}"

  tags:
  - always

- name: "bashrc | system | Installing bashrc."
  include: "install.yml"
  tags:
  - bashrc-system-bashrcdir-install

- block:

  - name: "bashrc | system | Symlinks"
    file:
      src: "{{ _symlink.src }}"
      dest: "{{ _symlink.dest }}"
      state: link
      force: yes
    with_items: "{{ _symlink_files|d([]) }}"
    loop_control:
      loop_var: _symlink
    when: _symlink is not none
          and (_symlink.src is not none and _symlink.src|d('')|length > 0)
          and (_symlink.dest is not none and _symlink.dest|d('')|length > 0)

  when: bashrc_install_path|d('')|length > 0
        and bashrc_install_path|is_dir == true
        and bashrc_bashrcdir_path|d('')|length > 0
        and bashrc_bashrcdir_path|is_dir == true
  vars:
    _symlink_files:
    - src: "{{ '%s/%s'|format(bashrc_install_path,bashrc_bashrc_name) }}"
      dest: "{{ '%s/bashrc'|format(bashrc_install_path) }}"
    - src: "{{ '%s/%s'|format(bashrc_install_path,bashrc_profile_name) }}"
      dest: "{{ '%s/profile'|format(bashrc_install_path) }}"
  tags:
  - bashrc-system-symlinks

