---
# tasks file for bashrc
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

- block:

  - name: "bashrc | user-homedir | Username."
    set_fact:
      bashrc_bash_user: "{{ tests_owner|d(user_name) }}"
    when: bashrc_bash_user|d('')|length <= 0

  - name: "bashrc | user-homedir | Get user '{{ bashrc_bash_user|d('???') }}' state."
    user:
      name: "{{ bashrc_bash_user }}"
      state: present
    register: bashrc_userhomedir_user_state
    ignore_errors: true
    when: bashrc_bash_user|d('')|length > 0

  - name: "bashrc | user-homedir | Stat user homedir."
    stat:
      path: "{{ bashrc_userhomedir_user_state.home
                if tests_run|d(false) == false
                and bashrc_userhomedir_user_state.home|d('')|length > 0
                and bashrc_userhomedir_user_state.home|is_dir|d(false) == true
                else '%s/home/%s'|format(tests_prefix_dir,tests_owner) }}"
    register: bashrc_userhomedir_st
    ignore_errors: true
    when: bashrc_userhomedir_user_state|d(none) is not none

  - name: "bashrc | user-homedir | Set fact user homedir."
    set_fact:
      bashrc_userhomedir_path: "{{
        bashrc_userhomedir_st.path|realpath }}"
      bashrc_userhomedir_owner: "{{
        tests_owner|d(bashrc_userhomedir_st.stat.pw_name) }}"
      bashrc_userhomedir_group: "{{
        tests_group|d(bashrc_userhomedir_st.stat.gr_name) }}"
    when: bashrc_userhomedir_st|d(none) is not none
          and bashrc_userhomedir_st.stat|d(none) is not none
          and bashrc_userhomedir_st.stat.isdir|d(false) == true

  tags:
  - always

