---
# tasks file for bashrc
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

- block:

  - name: "bashrc | userhomedir | {{ bashrc_userhomedir_user|d('???') }} - Stat user."
    user:
      name: "{{ bashrc_userhomedir_user }}"
      state: present
    register: bashrc_userhomedir_user_st
    ignore_errors: true
    vars:
      bashrc_userhomedir_user: "{{
        tests_owner|d(
        (bashrc_bash_user|d('',true)|string|trim|length > 0)|ternary(
        bashrc_bash_user|string|trim,lookup('pipe','id un')),true) }}"

  - name: "bashrc | userhomedir | {{ bashrc_userhomedir_user|d('???') }} - Stat user homedir."
    stat:
      path: "{{
        bashrc_userhomedir_user_st.home
        if tests_run|d(false,true) == false
        and bashrc_userhomedir_user_st.home|d('',true)|is_dir else
        '%s/home/%s'|format(tests_prefix_dir,tests_owner) }}"
    register: bashrc_userhomedir_st
    ignore_errors: true
    when: bashrc_userhomedir_user_st|d(none) is not none

  - name: "bashrc | userhomedir | {{ bashrc_userhomedir_user|d('???') }} - Set fact user homedir."
    set_fact:
      bashrc_userhomedir_path: "{{
        bashrc_userhomedir_st.path
        if ((bashrc_userhomedir_st|d({})).stat({})).isdir|d(false,true)
        and (bashrc_userhomedir_st|d({})).path|d('',true)|trim|lemgth > 0 else
        none }}"
      bashrc_userhomedir_owner: "{{
        tests_owner|d(
        ((bashrc_userhomedir_st|d({})).stat({})).isdir|d(false,true)|ternary(
        bashrc_userhomedir_st.stat.pw_name,none),true) }}"
      bashrc_userhomedir_group: "{{
        tests_group|d(
        ((bashrc_userhomedir_st|d({})).stat({})).isdir|d(false,true)|ternary(
        bashrc_userhomedir_st.stat.gr_name,none),true) }}"

  tags:
  - always

