---
# tasks file for bashrc
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

- block:

  - name: "bashrc | user | Get homedir."
    include: "user-homedir.yml"

  - name: "bashrc | user | Check the user homedir."
    fail:
      msg: "User '{{ bashrc_bash_user|d('???') }}' is not present in the this system."
    when: ( bashrc_userhomedir_path|d('')|length > 0
          and bashrc_userhomedir_path|realpath|is_dir == true ) == false

  - name: "bashrc | user | Facts - Build a install path."
    set_fact:
      bashrc_install_path: "{{
        '%s%s'|format(
        tests_prefix_dir|d(''),bashrc_install_prefix)|realpath
        if bashrc_install_prefix|d('')|length > 0 else
        bashrc_userhomedir_path|d('%s%s'|format(
        tests_prefix_dir|d(''),bashrc_base_prefix)|realpath) }}"

  - name: "bashrc | user | Facts - Set owner and group."
    set_fact:
      bashrc_install_owner: "{{
        tests_owner|d(
        bashrc_bash_user|d(user_name)
        if bashrc_bash_user|d(user_name|d(''))|length > 0 else
        bashrc_userhomedir_owner
        if bashrc_userhomedir_owner|d('')|length > 0 else
        bashrc_owner|d('root')) }}"
      bashrc_install_group: "{{
        tests_group|d(
        bashrc_userhomedir_group
        if bashrc_userhomedir_group|d('')|length > 0 else
        none }}"

  - name: "bashrc | user | Facts - Build a file and dir prefix."
    set_fact:
      bashrc_bashrcdir_prefix: "{{
        '.' if bashrc_install_prefix|d('')|length > 0
            and bashrc_install_prefix|d('')|realpath == bashrc_userhomedir_path|d('')
            else '' }}"

  - name: "bashrc | user | Facts - File and Dir name."
    set_fact:
      bashrc_bashrcdir_name: "{{
        '%s%s'|format(bashrc_bashrcdir_prefix|d(''),'bash.bashrc.d' }}"
      bashrc_bashrc_name: "{{
        '%s%s'|format(bashrc_bashrcdir_prefix,'bash.bashrc') }}"
      bashrc_profile_name: "{{
        '%s%s'|format(bashrc_bashrcdir_prefix,'bash.profile') }}"

  - name: "bashrc | user | Facts - Build a path of 'bash.bashrc.d'."
    set_fact:
      bashrc_bashrcdir_path: "{{
        '%s/%s'|format(bashrc_install_path,bashrc_bashrcdir_name) }}"

  - name: "bashrc | user | Create a bashrc install prefix."
    file:
      path: "{{ bashrc_install_path }}"
      state: directory
      owner: "{{ bashrc_install_owner }}"
      group: "{{ bashrc_install_group }}"
      mode: "{{ bashrc_dir_mode|d('0755') }}"
    when: bashrc_install_path|d('')|length > 0

  tags:
  - always

- name: "bashrc | user | Installing bashrc."
  include: "install.yml"
  tags:
  - bashrc-user-bashrcdir-install

- name: "bashrc | user | Setup bash user."
  set_fact:
    bashrc_bash_users:
    - "{{ bashrc_bash_user|d('') }}"
  tags:
  - bashrc-bash-users-set

