---
# vim: set ff=unix ts=2 sw=2 sts=2 et : This line is VIM modeline

language: python

python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Check bash version
  - bash --version
  # Install ansible
  - pip install ansible; ansible --version
  ## Create ansible.cfg with correct roles_path
  #- printf '[defaults]\nroles_path=../' >ansible.cfg

script:

  # Basic role syntax check, and tests-run
  - |
    set -x;
    tests_test_run=""
    tests_case_ret=0;
    ansible_play="ansible-playbook -i testcases test.yml"
    cd tests/ && {
      echo "ansible-playbook syntax-check." &&
      $ansible_play --syntax-check &&
      echo "ansible-playbook list-hosts." &&
      $ansible_play --list-hosts &&
      echo "ansible-playbook tests-run." &&
      for tests_casename in $( {
        cat testcases |
        egrep '^[ ]*[0-9A-Za-z][-_0-9A-Za-z.]*[ ]*(.+$|$)' |
        sort -u; } )
      do
        tests_test_run=yes
        echo "ansible-playbook tests-run [$tests_casename]."
        $ansible_play -l "${tests_casename}" ||
        tests_case_ret=$?
      done &&
      [ -n "${tests_test_run}" ] &&
      [ ${tests_case_ret:-1} -eq 0 ];
    } &&
    : "OK";

# Notifications
#notifications:
#  email:
#  - your@emailaddress

